# Generated by Django 5.2.4 on 2025-08-14 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Уникальный токен', max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('link', 'Привязка Telegram'), ('auth', 'Автовход на сайт')], help_text='Тип токена', max_length=10)),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Telegram ID (для привязки)', null=True)),
                ('expires_at', models.DateTimeField(help_text='Время истечения токена')),
                ('is_used', models.BooleanField(default=False, help_text='Использован ли токен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram токен',
                'verbose_name_plural': 'Telegram токены',
            },
        ),
    ]
