# Generated by Django 5.2.4 on 2025-08-14 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Содержание отзыва, предложения или сообщения об ошибке', verbose_name='Текст отзыва')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram (если отзыв из бота)', null=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания отзыва', verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, оставивший отзыв (может быть анонимным)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
