# Generated by Django 5.2.4 on 2025-07-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('typing', 'Ввод с клавиатуры'), ('matching', 'Сопоставление')], max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.IntegerField(default=0)),
                ('beginner_cards', models.IntegerField(default=0)),
                ('intermediate_cards', models.IntegerField(default=0)),
                ('advanced_cards', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('successful_reviews', models.IntegerField(default=0)),
                ('failed_reviews', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('tests_accuracy', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
