# Generated by Django 5.2.4 on 2025-07-09 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово на иностранном языке')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('example', models.CharField(blank=True, max_length=250, verbose_name='Пример')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Примечание')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='Дата следующего повторения')),
                ('last_repetition', models.DateField(verbose_name='Дата последнего повторения')),
                ('correct_answers', models.BooleanField(default=False, verbose_name='Был ли ответ верным')),
                ('interval', models.IntegerField(default=1, verbose_name='Интервал повторений (дни)')),
                ('easiness', models.FloatField(default=2.5, verbose_name='Коэффициент легкости')),
                ('repetitions_count', models.IntegerField(default=0, verbose_name='Количество повторений')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='words.card')),
            ],
        ),
    ]
