# Generated by Django 5.2.4 on 2025-07-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_repetition_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetition',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repetition',
            name='consecutive_successes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repetition',
            name='failed_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repetition',
            name='last_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repetition',
            name='successful_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repetition',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
