# Generated by Django 5.2.4 on 2025-07-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
